# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6118c7b92126cf6d6696752b484e336fd07c6b11d775d96395c70885965924e68fc872c540fe4e573477218d14d24a5d51c4594bddaa75f4ce5887d439571d15

test:
  secret_key_base: 27d9f48bb43afcbb1da7c788cc3363b64e482e7925d5205eaebe8ae1c7a0892ff8391b0099ae1a510b39d081543036a04a9a0d0ffff1b3ea7a1c8927ffcef6ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
